geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>', authapp.verify, name='verify')
]

geekshop/geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

import mainapp.views as mainapp


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', mainapp.index, name="index"),

    path('', include('social_django.urls', namespace='social')),

    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="authapp")),
    path('basket/', include('basketapp.urls', namespace="basket")),
    path('orders/', include('ordersapp.urls', namespace="ordersapp")),
    path('admin/', include('adminapp.urls', namespace="adminapp")),

    path('contact/', mainapp.contact, name="contact"),
    path('context/', mainapp.context),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/ordersapp/urls.py
from django.urls import path

from ordersapp import views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='list'),
    path('create/', ordersapp.OrderCreateView.as_view(), name='create'),
    path('update/<pk>', ordersapp.OrderUpdateView.as_view(), name='update'),
    path('read/<pk>', ordersapp.OrderDetailView.as_view(), name='read'),
    path('delete/<pk>', ordersapp.OrderDeleteView.as_view(), name='delete'),
    path('complete/<pk>', ordersapp.order_complete_view, name='complete'),
    path('product/<pk>/price/', ordersapp.get_product_price, name='get_product_price'),
]

geekshop/ordersapp/models.py
from django.db import models
from django.conf import settings

# Create your models here.

from mainapp.models import Product


class Order(models.Model):
    STATUS_FORMING = 'FM'
    STATUS_SENT_TO_PROCEED = 'STP'
    STATUS_PROCEEDED = 'PRD'
    STATUS_PAID = 'PD'
    STATUS_CANCELLED = 'CNL'
    STATUS_DONE = 'DN'

    STATUSES = (
        (STATUS_FORMING, 'формируется'),
        (STATUS_SENT_TO_PROCEED, 'отправлено в обработку'),
        (STATUS_PROCEEDED, 'обработано'),
        (STATUS_PAID, 'оплачено'),
        (STATUS_CANCELLED, 'отменено'),
        (STATUS_DONE, 'завершено')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUSES, default=STATUS_FORMING, max_length=3)

    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.pk)

    # def get_total_quantity(self):
    #     _items = self.orderitems.select_related()
    #     _total_quantity = sum(list(map(lambda x: x.quantity, _items)))
    #     return _total_quantity

    # def get_total_cost(self):
    #     _items = self.orderitems.select_related()
    #     _total_cost = sum(list(map(lambda x: x.quantity*x.product.price, _items)))
    #     return _total_cost

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, \
                                       items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ', related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

    # def delete(self):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super(self.__class__, self).delete()

geekshop/ordersapp/forms.py
from django import forms

from ordersapp.models import Order, OrderItem
from mainapp.models import Product


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

        self.fields['product'].queryset = Product.objects.filter(is_active=True).select_related()

geekshop/ordersapp/views.py
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from django.shortcuts import render, get_object_or_404

# Create your views here.
from basketapp.models import Basket
# from ordersapp.forms import OrderItemForm
from mainapp.models import Product
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem


class OrderListView(ListView):
    # здесь шаблон можно не оказывать, поскольку для данного имени класса и структуры папок шаблонов
    # автоматом будет вестись поиск шаблона в папке  /templates/order_list.html
    model = Order

    def get_queryset(self):
        # return super().get_queryset().filter(is_active=True)
        return super().get_queryset().filter(is_active=True).select_related()


class OrderCreateView(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            # basket_items = Basket.objects.filter(user=self.request.user)
            basket_items = Basket.objects.filter(user=self.request.user).select_related()
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
            else:
                formset = OrderFormSet()

        context_data['orderitems'] = formset
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
            # basket_items = Basket.objects.filter(user=self.request.user)
            basket_items = Basket.objects.filter(user=self.request.user).select_related()
            basket_items.delete()

        # удаляем пустой заказ
        if self.object.get_summary()['total_cost'] == 0:
            self.object.delete()
        #
        return super().form_valid(form)


class OrderUpdateView(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            # formset = OrderFormSet(instance=self.object)
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance=self.object, queryset=queryset)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        context_data['orderitems'] = formset
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_summary()['total_cost'] == 0:
            self.object.delete()

        return super().form_valid(form)


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:list')


class OrderDetailView(DetailView):
    model = Order


def order_complete_view(request, pk):
    order_item = Order.objects.get(pk=pk)
    order_item.status = Order.STATUS_SENT_TO_PROCEED
    order_item.save()

    return HttpResponseRedirect(reverse('ordersapp:list'))


@receiver(pre_save, sender=OrderItem)
# @receiver(pre_save, sender=Basket)
def product_quantity_update_on_save(sender, update_fields, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=OrderItem)
# @receiver(pre_delete, sender=Basket)
def product_quantity_update_on_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


def get_product_price(request, pk):
    _price = 0
    # if request.is_ajax():
    #     _product = get_object_or_404(Product, pk=pk)
    _product = Product.objects.get(pk=int(pk))
    if _product:
        _price = _product.price

    return JsonResponse({'price': _price})

geekshop/ordersapp/templates/ordersapp/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/orders_scripts.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="order_container">
    <div class="h2 text-center head">
        Работа с заказами
    </div>

    {% block content %}

    {% endblock %}
</div>
</body>
</html>

geekshop/ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends "ordersapp/base.html" %}

{% block content %}
<div class="category_delete">
    <div class="h1">Уверены, что хотите удалить</div>
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <form action="{% url 'ordersapp:delete' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'ordersapp:list' %}">отмена</a>
    </button>
</div>

{%  endblock content %}

geekshop/ordersapp/templates/ordersapp/order_detail.html
{{% extends "ordersapp/base.html" %}
{% load static %}
{% load my_tags %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <img src="media/{{ item.product.image }}"
                    alt="{{ item.product.short_desc }}">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load cache %}

{% block content %}
{% include 'ordersapp/includes/inc_order_summary.html' %}
<div class="order_form">
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <table class="table">
            {{ orderitems.management_form }}
            {% for form in orderitems.forms %}
            {% if forloop.first %}
            <thead>
            <tr>
                {% for field in form.visible_fields %}
                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order">
                    {{ field.label|capfirst }}
                </th>
                {% endfor %}
            </tr>
            </thead>
            {% endif %}
            <tr class="formset_row">
                {% for field in form.visible_fields %}
                <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order">
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {% if field.name == 'price' %}
                        {% if field.value %}
                            <span class="orderitems-{{forloop.parentloop.counter0}}-price">{{ field.value }}</span> руб.
                        {% endif %}
                    {% else %}
                        {% if field.name == 'product' %}
                            {% cache 3600 orderitemform_product field.value %}
                                {{ field }}
                            {% endcache %}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endif %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
        <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
        {% include 'ordersapp/includes/inc_order_actions.html' %}
    </form>
</div>

{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
<div class="h2 text-center head">
       Ваши заказы,
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created_at|date:"Y-m-d H:i" }}</td>
                   <td>{{ item.updated_at|date:"Y-m-d H:i" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
   <button class="btn btn-default btn-round">
       <a href="{% url 'index' %}">на главную</a>
   </button>
    <br>
    <br>
   <button class="btn btn-default btn-round">
       <a href="{% url 'ordersapp:create' %}">новый заказ</a>
   </button>

{% endblock %}