geekshop/adminapp/urls.py
from django.urls import path
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
 path('users', adminapp.UsersListView.as_view(), name='users'),
 path('user_create/', adminapp.user_create, name='user_create'),
 path('user_update/<int:pk>', adminapp.user_update, name='user_update'),
 path('user_delete/<int:pk>', adminapp.user_delete, name='user_delete'),

 path('categories', adminapp.categories, name='categories'),
 path('category_create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
 path('category_update/<int:pk>', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
 path('category_delete/<int:pk>', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

 path('products/<int:pk>', adminapp.products, name='products'),
 path('product_create/<int:pk>', adminapp.ProductCreateView.as_view(), name='product_create'),
 path('product_update/<int:pk>', adminapp.product_update, name='product_update'),
 path('product_delete/<int:pk>', adminapp.product_delete, name='product_delete'),
 path('product_read/<int:pk>', adminapp.ProductDetailView.as_view(), name='product_read'),
]

geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>', authapp.verify, name='verify')
]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
 path('', basketapp.basket, name='basket'),
 path('add/<int:pk>/', basketapp.basket_add, name='basket_add'),
 path('remove/<int:pk>/', basketapp.basket_remove, name='basket_remove')
]

geekshop/geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

import mainapp.views as mainapp


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', mainapp.index, name="index"),

    path('', include('social_django.urls', namespace='social')),

    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="authapp")),
    path('basket/', include('basketapp.urls', namespace="basket")),
    path('orders/', include('ordersapp.urls', namespace="ordersapp")),
    path('admin/', include('adminapp.urls', namespace="adminapp")),

    path('contact/', mainapp.contact, name="contact"),
    path('context/', mainapp.context),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path

from mainapp import views as mainapp

app_name = 'products'

urlpatterns = [
    path('', mainapp.products, name="products"),
    path('<int:pk>', mainapp.products, name="category"),
    path('<int:pk>/<int:page>', mainapp.products, name='product_paginator'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/ordersapp/urls.py
from django.urls import path

from ordersapp import views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='list'),
    path('create/', ordersapp.OrderCreateView.as_view(), name='create'),
    path('update/<pk>', ordersapp.OrderUpdateView.as_view(), name='update'),
    path('read/<pk>', ordersapp.OrderDetailView.as_view(), name='read'),
    path('delete/<pk>', ordersapp.OrderDeleteView.as_view(), name='delete'),
    path('complete/<pk>', ordersapp.order_complete_view, name='complete'),
    path('product/<pk>/price/', ordersapp.get_product_price, name='get_product_price'),
]

geekshop/mainapp/models.py
from django.db import models


# Create your models here.


class ProductCategotry(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Имя')
    description = models.TextField(verbose_name='Описание', blank=True)
    link_name = models.CharField(max_length=64, unique=False, verbose_name='Ссылка', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def delete(self, *args, **kwargs):
        self.is_active = False;
        self.save()


class Product(models.Model):
    category = models.ForeignKey(ProductCategotry, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

geekshop/mainapp/views.py
import json
import random

from django.conf import settings
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.decorators.cache import cache_page, never_cache

from mainapp import models
from mainapp.models import Product, ProductCategotry


def get_hot_product():
    products_list = Product.objects.filter(is_active=True, category__is_active=True)
    return random.sample(list(products_list), 1)[0]


def get_same_products(hot_product):
    same_products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)
    return same_products_list[:3]


def index(request):
    # product_list = Product.objects.filter(is_active=True, category__is_active=True)[:4]
    product_list = Product.objects.filter(is_active=True, category__is_active=True).select_related()[:4]
    context = {
        'title': 'магазин',
        'products': product_list,
    }
    return render(request, "mainapp/index.html", context)


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategotry.objects.filter(is_active=True).select_related()
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategotry.objects.filter(is_active=True).select_related()


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategotry, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategotry, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True,
                                              category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True,
                                      category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


# @cache_page(3600)
@never_cache
def products(request, pk=None, page=1):
    # links_menu = ProductCategotry.objects.filter(is_active=True)
    # links_menu = ProductCategotry.objects.filter(is_active=True).select_related()
    links_menu = get_links_menu()
    title = 'продукты'

    if pk is not None:
        if pk == 0:
            category_item = {
                'pk': 0,
                'name': 'все'
            }
            product_list = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category_item = get_object_or_404(ProductCategotry, pk=pk)
            product_list = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True) \
                .order_by('price')

        paginator = Paginator(product_list, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'products': products_paginator,
            'category': category_item,
        }
        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }

    return render(request, 'mainapp/products.html', content)


def contact(request):
    with open("json/contact_info.json") as read_f:
        adresses = json.load(read_f)

    context = {
        'title': 'Контакты',
        'addresses': adresses,
    }
    return render(request, "mainapp/contact.html", context)


def context(request):
    with open("json/my.json") as read_f:
        some_info = json.load(read_f)

    context = {
        'title': "Title",
        'header': "header",
        'username': "Джон",
        'products': [{'name': 'one', 'price': 1}, {'name': 'two', 'price': 10}, {'name': 'three', 'price': 15}]
    }
    return render(request, "mainapp/test_context.html", context)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        # 'links_menu': ProductCategotry.objects.filter(is_active=True),
        # 'links_menu': ProductCategotry.objects.filter(is_active=True).select_related(),
        'links_menu': get_links_menu(),
        # 'product': get_object_or_404(Product, pk=pk),
        'product': get_product(pk),
    }

    return render(request, 'mainapp/product.html', content)

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li><a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.kwargs.pk == link.pk %}active{% endif%}">все</a></li>
    {% for link in links_menu %}
    <li><a href="{% url 'products:category' link.pk %}" class="{% if request.resolver_match.kwargs.pk == link.pk %}active{% endif%}">{{link.name}}</a></li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="index.html" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'index' %}"
           class="{% if request.resolver_match.url_name == 'index' %}active{% endif%}">домой</a></li>
    <li><a href="{% url 'products:products' %}"
           class="{% if request.resolver_match.namespace == 'products' %}active{% endif%}">продукты</a></li>
    <li><a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif%}">контакты</a>
    </li>
     <!--   //////////////////////////////////////////////////////////////////////////-->
    {% if user.is_authenticated %}
    <li>
        <div class="dropdown">
            <a class="dropdown-toggle" href="" data-toggle="dropdown">
                {{ user.first_name|default:'Пользователь' }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="{% url 'authapp:edit' %}">
                        профиль
                    </a>
                </li>
                <li>
                    <a href="{% url 'ordersapp:list' %}">
                        заказы
                    </a>
                </li>
            </ul>
        </div>
    </li>
    {% endif %}
    {% if user.is_superuser %}
    <li>
        <a href="{% url 'adminapp:users' %}">админка</a>
    </li>
    {% endif %}
    <!--   //////////////////////////////////////////////////////////////////////////-->

    {% if user.is_authenticated %}
<!--        {% if user.is_superuser%}-->
<!--        <li><a href="{% url 'adminapp:users' %}">Админка</a></li>-->
<!--        {% endif %}-->
<!--        <li><a href="{% url 'authapp:edit' %}">{{ user.first_name|default:'Пользователь' }}</a></li>-->
<!--        <li><a href="{% url 'ordersapp:list' %}">Заказы</a></li>-->
        <li><a href="{% url 'authapp:logout' %}">выйти</a></li>
    {% else %}
        <li><a href="{% url 'authapp:register' %}">Регистрация</a></li>
        <li><a href="{% url 'authapp:login' %}">Войти</a></li>
    {% endif %}

</ul>
<a href="#" class="search"></a>
<a href="{% url 'basketapp:basket' %}" class="basket">
    <span>
        {% if basket %}
        {{basket.0.total_cost|floatformat:0}} руб.<br>
        ({{basket.0.total_quantity}} шт.)
        {% endif %}
    </span>
</a>