geekshop/adminapp/urls.py
from django.urls import path
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
 path('users', adminapp.UsersListView.as_view(), name='users'),
 path('user_create/', adminapp.user_create, name='user_create'),
 path('user_update/<int:pk>', adminapp.user_update, name='user_update'),
 path('user_delete/<int:pk>', adminapp.user_delete, name='user_delete'),

 path('categories', adminapp.categories, name='categories'),
 path('category_create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
 path('category_update/<int:pk>', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
 path('category_delete/<int:pk>', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

 path('products/<int:pk>', adminapp.products, name='products'),
 path('product_create/<int:pk>', adminapp.ProductCreateView.as_view(), name='product_create'),
 path('product_update/<int:pk>', adminapp.product_update, name='product_update'),
 path('product_delete/<int:pk>', adminapp.product_delete, name='product_delete'),
 path('product_read/<int:pk>', adminapp.ProductDetailView.as_view(), name='product_read'),
]

geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>', authapp.verify, name='verify')
]

geekshop/geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

import mainapp.views as mainapp


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', mainapp.index, name="index"),

    path('', include('social_django.urls', namespace='social')),

    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="authapp")),
    path('basket/', include('basketapp.urls', namespace="basket")),
    path('orders/', include('ordersapp.urls', namespace="ordersapp")),
    path('admin/', include('adminapp.urls', namespace="adminapp")),

    path('contact/', mainapp.contact, name="contact"),
    path('context/', mainapp.context),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategotry, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategotry
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategotry, Product

from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategotry)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     context = {
#         'object_list': ShopUser.objects.all().order_by('-is_active')
#     }
#     return render(request, 'adminapp/users_list.html', context)

class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users_list.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:users'))
    else:
        user_form = ShopUserRegisterForm()

    content = {'title': title, 'update_form': user_form}

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    content = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user.delete()
        # вместо удаления лучше сделаем неактивным
        # user.is_active = False
        # user.save()
        return HttpResponseRedirect(reverse('adminapp:users'))

    content = {'title': title, 'user_to_delete': user}

    return render(request, 'adminapp/user_delete.html', content)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    context = {
        'object_list': ProductCategotry.objects.all()
    }
    return render(request, 'adminapp/categories_list.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     title = 'Создание категории'
#
#     if request.method == 'POST':
#         cat_form = ProductCategoryEditForm(request.POST)
#         if cat_form.is_valid():
#             cat_form.save()
#             return HttpResponseRedirect(reverse('adminapp:categories'))
#     else:
#         cat_form = ProductCategoryEditForm()
#
#     content = {'title': title, 'form': cat_form}
#
#     return render(request, 'adminapp/category_update.html', content)


class ProductCategoryCreateView(CreateView):
    model = ProductCategotry
    template_name = 'adminapp/category_update.html'
    # fields = __all__
    form_class = ProductCategoryEditForm
    success_url = reverse_lazy('adminapp:categories')


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = 'Редактирование категории'
#
#     edit_cat = get_object_or_404(ProductCategotry, pk=pk)
#     if request.method == 'POST':
#         edit_form = ProductCategoryEditForm(request.POST, instance=edit_cat)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('adminapp:category_update', args=[edit_cat.pk]))
#     else:
#         edit_form = ProductCategoryEditForm(instance=edit_cat)
#
#     content = {'title': title, 'edit_form': edit_form}
#
#     return render(request, 'adminapp/category_update.html', content)

class ProductCategoryUpdateView(UpdateView):
    model = ProductCategotry
    template_name = 'adminapp/category_update.html'
    # fields = __all__
    form_class = ProductCategoryEditForm
    success_url = reverse_lazy('adminapp:categories')

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)

        return super().form_valid(form)


# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     title = 'Удаление категории'
#
#     _cat = get_object_or_404(ProductCategotry, pk=pk)
#
#     if request.method == 'POST':
#         # user.delete()
#         # вместо удаления лучше сделаем неактивным
#         _cat.is_active = False
#         _cat.save()
#         return HttpResponseRedirect(reverse('adminapp:categories'))
#
#     content = {'title': title, 'category_to_delete': _cat}
#
#     return render(request, 'adminapp/category_delete.html', content)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategotry
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('adminapp:categories')

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.success_url)


def products(request, pk):
    category_item = get_object_or_404(ProductCategotry, pk=pk)
    context = {
        'category': category_item,
        'object_list': Product.objects.filter(category__pk=pk)
    }
    return render(request, 'adminapp/product_list.html', context)


# def product_create(request, pk):
#     category_item = get_object_or_404(ProductCategotry, pk=pk)
#     title = 'Создание продукта'
#
#     if request.method == 'POST':
#         product_form = ProductEditForm(request.POST, request.FILES)
#         if product_form.is_valid():
#             product_form.save()
#             return HttpResponseRedirect(reverse('adminapp:products', args=[pk]))
#     else:
#         product_form = ProductEditForm({'category': category_item})
#     content = {'title': title, 'edit_form': product_form, 'category': category_item}
#
#     return render(request, 'adminapp/product_update.html', content)

class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    form_class = ProductEditForm
    success_url = reverse_lazy('adminapp:categories')

    def _get_category(self):
        category_id = self.kwargs.get('pk')
        category_item = get_object_or_404(ProductCategotry, pk=category_id)
        return category_item

    def get_success_url(self):
        return reverse('adminapp:products', args=[self._get_category().pk])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get('pk')
        category_item = get_object_or_404(ProductCategotry, pk=category_id)
        context['category'] = category_item

        return context


def product_update(request, pk):
    title = 'Редактирование продукта'

    edit_product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('adminapp:product_update', args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)

    content = {'title': title, 'form': edit_form, 'category': edit_product.category}

    return render(request, 'adminapp/product_update.html', content)


def product_delete(request, pk):
    title = 'Удаление продукта'

    product_to_delete = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        # user.delete()
        # вместо удаления лучше сделаем неактивным
        product_to_delete.is_active = False
        product_to_delete.save()
        return HttpResponseRedirect(reverse('adminapp:products', args=[product_to_delete.category.pk]))

    content = {'title': title, 'product_to_delete': product_to_delete}

    return render(request, 'adminapp/product_delete.html', content)


# def product_read(request, pk):
#     title = 'продукт/подробнее'
#     product = get_object_or_404(Product, pk=pk)
#     content = {'title': title, 'object': product}
#
#     return render(request, 'adminapp/product_read.html', content)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
      Админка
    </div>
    <div class="admin_menu">
        <ul class="menu">
            <li>
                <a href="{% url 'index' %}">На сайт</a>
            </li>
            <li>
                <a href="{% url 'adminapp:users' %}">Пользователи</a>
            </li>
            <li>
                <a href="{% url 'adminapp:categories' %}">Категории</a>
            </li>
        </ul>


    </div>
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories_list.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="categories_list">
    <a class="btn btn-primary" style="color: white" href="{% url 'adminapp:category_create' %}">Новая категория</a>
    {% for object in object_list %}
    <div class="category_record {% if not object.is_active %}not_active{% endif %}">
        <div class="category_name">
            {{ object.name|title }}
        </div>
        <div class="category_actions">

            <button>
                <a class='btn' href="{% url 'adminapp:category_update' object.pk %}">
                    редактировать
                </a>
            </button>
            <button>
                <a class='btn' href="{% url 'adminapp:category_delete' object.pk %}">
                    удалить
                </a>
            </button>
            <button>
                <a class='btn' href="{% url 'adminapp:products' object.pk %}">
                    товары категории
                </a>
            </button>
        </div>
        <div class="category_desc">
            {{ object.description|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="category_delete">
    Уверены, что хотите удалить {{ object.name }}
    <form action="{% url 'adminapp:category_delete' object.pk %}"
          method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'adminapp:categories' %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:categories' %}">К списку категорий</a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="product_delete">
    Уверены, что хотите удалить {{ product_to_delete.name }}
    <form action="{% url 'adminapp:product_delete' product_to_delete.pk %}"
          method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'adminapp:products' product_to_delete.category.pk %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_list.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
  <div class="products_list">
    <button class="btn btn-info new_product">
      <a href="{% url 'adminapp:product_create' category.pk %}">
        новый продукт
      </a>
    </button>

    {% for object in object_list %}
      <div class="product_record {% if not object.is_active %}not_active{% endif %}">
<!--        <img src="/media/{{object.image|default:'products_images/default.jpg'}}" alt="{{ object.name }}">-->
        <img src="{{object.image|media_for_products}}" alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href="{% url 'adminapp:product_read' object.pk %}">
              подробнее
            </a>
          </button>
          <button>
            <a href="{% url 'adminapp:product_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'adminapp:product_delete' object.pk %}">
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ object.category.name|title }} / 
                     {{ object.name|title }}</strong> 
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
         alt="{{ object.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ object.price }} руб</p>
      <b>количество</b>
      <p>{{ object.quantity }}</p>
      <b>в каталоге</b>
      <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href="{% url 'adminapp:product_update' object.pk %}">
            редактировать
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href="{% url 'adminapp:product_delete' object.pk %}">
            удалить
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href="{% url 'adminapp:products' object.category.pk %}">
            назад
          </a>
        </button>
      </p>
    </div>
    <div class="product_desc">
      <b>краткая информация</b>
      <p>{{ object.short_desc }}</p>
      <br><br>
      <b>подробная информация</b>
      <p>{{ object.description }}</p>
    </div>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:products' category.pk %}">К списку продуктов категории</a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_delete">
    Уверены, что хотите удалить {{ user_to_delete.username }}
    {% if user_to_delete.first_name %}
        ({{ user_to_delete.first_name|title }}
        {% if user_to_delete.last_name %}
            {{ user_to_delete.last_name|title }}
        {% endif %})
    {% endif %}
    <form action="{% url 'adminapp:user_delete' user_to_delete.pk %}"
          method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'adminapp:users' %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users_list.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}

{% block content%}
<div class="users_list">
    <a class="btn btn-primary" style="color: white" href="{% url 'adminapp:user_create' %}">Добавить пользователя</a>
    {% for item in object_list %}
    <div class="user_record {% if not item.is_active %}not_active{% endif %}" >
        <div class="user_avatar">
<!--            <img src="/media/{{item.avatar|default:'users/product-5-sm.jpg'}}"/>-->
            <img src="{{ item.avatar|media_for_users }}"/>
        </div>
        <div class="user_role">
            {% if item.is_superuser %}
            Администратор
            {% else %}
            Пользователь
            {% endif %}
            <a class="btn btn-info" href="{% url 'adminapp:user_update' item.pk %}">Изменить</a>
            <br><br>
            <a class="btn btn-info" href="{% url 'adminapp:user_delete' item.pk %}">Удалить</a>
        </div>
        <div class="user_name">
            <p>{{ item.username }}</p>
            <p>{{ item.get_full_name }}</p>
        </div>
        <div class="user_age"><p>{{item.age}}</p></div>
        <div class="user_email"><p>{{item.email}}</p></div>
    </div>
    {% endfor %}
</div>
{% endblock content%}