geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>', authapp.verify, name='verify')
]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
 path('', basketapp.basket, name='basket'),
 path('add/<int:pk>/', basketapp.basket_add, name='basket_add'),
 path('remove/<int:pk>/', basketapp.basket_remove, name='basket_remove')
]

geekshop/geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

import mainapp.views as mainapp


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', mainapp.index, name="index"),

    path('', include('social_django.urls', namespace='social')),

    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="authapp")),
    path('basket/', include('basketapp.urls', namespace="basket")),
    path('orders/', include('ordersapp.urls', namespace="ordersapp")),
    path('admin/', include('adminapp.urls', namespace="adminapp")),

    path('contact/', mainapp.contact, name="contact"),
    path('context/', mainapp.context),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path

from mainapp import views as mainapp

app_name = 'products'

urlpatterns = [
    path('', mainapp.products, name="products"),
    path('<int:pk>', mainapp.products, name="category"),
    path('<int:pk>/<int:page>', mainapp.products, name='product_paginator'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models


# Create your models here.


class ProductCategotry(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Имя')
    description = models.TextField(verbose_name='Описание', blank=True)
    link_name = models.CharField(max_length=64, unique=False, verbose_name='Ссылка', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def delete(self, *args, **kwargs):
        self.is_active = False;
        self.save()


class Product(models.Model):
    category = models.ForeignKey(ProductCategotry, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

geekshop/mainapp/views.py
import json
import random

from django.conf import settings
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.decorators.cache import cache_page, never_cache

from mainapp import models
from mainapp.models import Product, ProductCategotry


def get_hot_product():
    products_list = Product.objects.filter(is_active=True, category__is_active=True)
    return random.sample(list(products_list), 1)[0]


def get_same_products(hot_product):
    same_products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)
    return same_products_list[:3]


def index(request):
    # product_list = Product.objects.filter(is_active=True, category__is_active=True)[:4]
    product_list = Product.objects.filter(is_active=True, category__is_active=True).select_related()[:4]
    context = {
        'title': 'магазин',
        'products': product_list,
    }
    return render(request, "mainapp/index.html", context)


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategotry.objects.filter(is_active=True).select_related()
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategotry.objects.filter(is_active=True).select_related()


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategotry, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategotry, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True,
                                              category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True,
                                      category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


# @cache_page(3600)
@never_cache
def products(request, pk=None, page=1):
    # links_menu = ProductCategotry.objects.filter(is_active=True)
    # links_menu = ProductCategotry.objects.filter(is_active=True).select_related()
    links_menu = get_links_menu()
    title = 'продукты'

    if pk is not None:
        if pk == 0:
            category_item = {
                'pk': 0,
                'name': 'все'
            }
            product_list = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category_item = get_object_or_404(ProductCategotry, pk=pk)
            product_list = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True) \
                .order_by('price')

        paginator = Paginator(product_list, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'products': products_paginator,
            'category': category_item,
        }
        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }

    return render(request, 'mainapp/products.html', content)


def contact(request):
    with open("json/contact_info.json") as read_f:
        adresses = json.load(read_f)

    context = {
        'title': 'Контакты',
        'addresses': adresses,
    }
    return render(request, "mainapp/contact.html", context)


def context(request):
    with open("json/my.json") as read_f:
        some_info = json.load(read_f)

    context = {
        'title': "Title",
        'header': "header",
        'username': "Джон",
        'products': [{'name': 'one', 'price': 1}, {'name': 'two', 'price': 10}, {'name': 'three', 'price': 15}]
    }
    return render(request, "mainapp/test_context.html", context)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        # 'links_menu': ProductCategotry.objects.filter(is_active=True),
        # 'links_menu': ProductCategotry.objects.filter(is_active=True).select_related(),
        'links_menu': get_links_menu(),
        # 'product': get_object_or_404(Product, pk=pk),
        'product': get_product(pk),
    }

    return render(request, 'mainapp/product.html', content)

geekshop/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{{title|default:"магазин"|title}}{% endblock %}</title>

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
       <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
       <script src="{% static 'js/bootstrap.min.js' %}"></script>
   {% endblock %}

</head>
<body>
<div class="container">
    {% block menu %} {% endblock menu %}

    {% block content%} {% endblock content%}

    <div class="clr"></div>
</div>

{% block footer %}
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB {% now "Y" %}</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
</div>
{% endblock footer %}
</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
<div class="hero">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
    <h1>наши контакты</h1>
</div>
{% endblock menu %}

{% block content%}
<div class="location">
    {% for addr in addresses %}
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>{{addr.city}}</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>{{addr.phone}}</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>{{addr.email}}</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>{{address}}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content%}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
<div class="slider">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="{% url 'products:products' %}" class="button-order">заказать <img src="{% static 'img/arrow.png'%}" alt=""></a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>
{% endblock menu %}

{% block content%}
<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        {% for product in products %}
        <div class="block">
            <a href="{% url 'products:product' product.pk  %}"><img src="/media/{{ product.image }}" alt="">
            <div class="text">
                <img src="{% static 'img/icon-hover.png' %}" alt="img">
                <h4>{{product.name}}</h4>
                <p>{{product.category.name}}</p>
                <p>{{product.short_desc}}</p>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content%}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
</div>
{% endblock menu %}

{% block content%}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.image }}" alt="product">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{product.name}}</h3>
            <h3 class="red">{{product.category}}</h3>
            <p class="price"> {{product.price|floatformat:2}} <span>руб</span></p>
            <a href="{% url 'basketapp:basket_add' product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>{{product.short_desc}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
</div>
{% endblock menu %}

{% block content%}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ hot_product.image }}" alt="hot product">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{hot_product.name}}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price"> {{hot_product.price|floatformat:2}} <span>руб</span></p>
            <a href="{% url 'products:product' hot_product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>{{hot_product.short_desc}}</p>
            </div>
        </div>
    </div>
    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="related-products clearfix">
            {% for product in same_products%}
            <div class="block">
                <a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png'%}" alt="img">
                        <h4>{{product.name}}</h4>
                        <p>{{product.short_desc}} </p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content%}

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
        <div class="title clearfix">
            <h2>
                Категория: "{{ category.name|title }}"
            </h2>
            <div class="paginator">
          {% if products.has_previous %}
            <a href="{% url 'products:product_paginator' category.pk products.previous_page_number %}"><</a>
          {% endif %}
          <span class="current"> страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
          {% if products.has_next %}
            <a href="{% url 'products:product_paginator' category.pk products.next_page_number %}">></a>
          {% endif %}
        </div>
        </div>
        <div class="category-products clearfix">

            {% for product in products %}
            <div class="block">
                <a href="{% url 'products:product' product.pk %}">
                    <img src="/media/{{ product.image }}" alt="product">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.description }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="clr"></div>

{% endblock %}

geekshop/mainapp/templates/mainapp/test_context.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{header}}</title>
</head>
<body>
<h1>{{header}}</h1>
<p1>{{username}}</p1>
{%for product in products%}
    <h3>{{product.name}}</h3>
    <p>{{product.price}}</p>
{% endfor %}
</body>
</html>